services:
  labgoloadtest:
    image: labgoloadtest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  k6:
    image: loadimpact/k6
    build: ./k6
    environment:
      - COUNT=1000
      - URL=http://labgoloadtest:3000/hit
      - DURATION=1s
    # service container count
    deploy:
      replicas: 10
